#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wclean libso turbulenceModels/pPFTurbulenceModel
wclean libso turbulenceModels/pPFRAS
wclean libso turbulenceModels/pPFLES
wclean libso porosityModels
wclean
